server:
  port: 9280

spring:
  application:
    name: "spring-boot-application"
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:persondb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
