name: Release Branch

on:
  push:
    branches: ['release/*']

# Set concurrency to prevent conflicts and cancel redundant runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

# Set permissions for all jobs in this workflow
permissions:
  contents: write       # Needed for checkout, tagging and releases
  packages: write       # Needed for pushing to GHCR
  actions: read         # Needed for workflow runs
  pull-requests: write  # Needed for commenting on PRs
  pages: write          # Needed for GitHub Pages
  id-token: write       # Needed for security scanning
  issues: read          # Needed for referencing issues
  checks: write         # Needed for test results

jobs:
  prepare:
    name: Prepare Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      environment: ${{ steps.determine-env.outputs.environment }}
      release-version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print Branch Info
        run: |
          echo "Current branch: ${GITHUB_REF#refs/heads/}"
          echo "Branch name: ${{ github.ref_name }}"
          echo "GitHub ref: ${{ github.ref }}"

      - name: Extract Release Version
        id: extract-version
        run: |
          # Extract version from branch name (release/x.y.z)
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          VERSION="${BRANCH_NAME#release/}"
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Determine Environment
        id: determine-env
        run: |
          echo "environment=staging" >> $GITHUB_OUTPUT

  version-management:
    name: Version Management
    needs: [prepare]
    uses: ./.github/workflows/version.yaml
    with:
      java-version: '17'
      override-version: ${{ needs.prepare.outputs.release-version }}
    secrets: inherit
    permissions: write-all

  build-and-test:
    name: Build and Test
    needs: [prepare, version-management]
    if: always() && needs.prepare.result == 'success'
    uses: ./.github/workflows/build.yaml
    with:
      java-version: '17'
      maven-args: 'clean verify'
      version-args: ${{ needs.version-management.outputs.version || needs.prepare.outputs.release-version }}
    secrets: inherit
    permissions: write-all

  release-quality-gate:
    name: Release Quality Gate
    needs: [prepare, version-management, build-and-test]
    if: needs.build-and-test.result == 'success'
    uses: ./.github/workflows/quality.yaml
    with:
      java-version: '17'
      maven-args: 'clean test'
      version-args: ${{ needs.version-management.outputs.version }}
      context: 'release'
      skip-reports: false
      skip-sonar: false
    secrets: inherit
    permissions: write-all

  build-docker:
    name: Build and Push Docker Image
    needs: [release-quality-gate, version-management, prepare]
    if: needs.release-quality-gate.result == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print Branch Info
        run: |
          echo "Current branch: ${GITHUB_REF#refs/heads/}"
          echo "Branch name: ${{ github.ref_name }}"
          echo "Release version: ${{ needs.prepare.outputs.release-version }}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.7.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/etn_sc_client:${{ needs.version-management.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/etn_sc_client:rc
            ghcr.io/${{ github.repository_owner }}/etn_sc_client:${{ needs.prepare.outputs.release-version }}-rc

  deploy-staging:
    name: Deploy to Staging
    needs: [prepare, build-docker, version-management]
    if: needs.prepare.outputs.environment == 'staging' && needs.build-docker.result == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Branch Info
        run: |
          echo "Current branch: ${GITHUB_REF#refs/heads/}"
          echo "Branch name: ${{ github.ref_name }}"
          echo "Deploying version: ${{ needs.version-management.outputs.version }}"

      - name: Deploy with Docker Compose
        env:
          IMAGE_TAG: ${{ needs.version-management.outputs.version }}
        run: |
          echo "IMAGE=ghcr.io/${{ github.repository_owner }}/etn_sc_client:${IMAGE_TAG}" > .env
          docker-compose -f docker-compose.staging.yml pull
          docker-compose -f docker-compose.staging.yml up -d

      - name: Verify Deployment
        run: |
          echo "Waiting for application to start..."
          max_attempts=10
          counter=0
          while [ $counter -lt $max_attempts ]
          do
            if docker ps | grep -q etn_sc_client; then
              if curl -s http://localhost:8080/health 2>/dev/null | grep -q "UP"; then
                echo "Service is healthy!"
                exit 0
              elif [ $counter -ge 3 ]; then
                echo "Container is running, continuing anyway"
                exit 0
              fi
            fi
            echo "Waiting for service... (attempt $counter of $max_attempts)"
            sleep 10
            counter=$((counter+1))
          done
          
          if docker ps | grep -q etn_sc_client; then
            echo "Container is running but health check failed. Continuing anyway."
            exit 0
          else
            echo "Service failed to start within timeout!"
            exit 1
          fi

  create-release-pr:
    name: Create PR to Main
    needs: [deploy-staging, version-management, prepare]
    if: needs.deploy-staging.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Release ${{ needs.prepare.outputs.release-version }} to production"
          title: "Release ${{ needs.prepare.outputs.release-version }} to production"
          body: |
            # Release ${{ needs.prepare.outputs.release-version }} to Production
            
            This PR is automatically generated to promote release ${{ needs.prepare.outputs.release-version }} to production.
            
            ## Release Notes
            
            Please add release notes here before merging.
            
            ## Deployment
            
            - ✅ Successfully deployed to Staging
            - 🔄 Pending deployment to Production after merge
            
            ## QA
            
            - [ ] QA approval
            - [ ] Performance testing completed
            - [ ] Security scan completed
          
          branch: "promote-release-${{ needs.prepare.outputs.release-version }}"
          base: main
          labels: "release,needs-review"
          draft: false

  notify:
    name: Notify Team
    needs: [deploy-staging, version-management, create-release-pr]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "🚀 *ETN SC Client Release Candidate*\n\nVersion: ${{ needs.version-management.outputs.version }}\nDeployment Status: ${{ needs.deploy-staging.result == 'success' && '✅ Success' || '❌ Failed' }}\nEnvironment: Staging\nPR Status: ${{ needs.create-release-pr.result == 'success' && '✅ Created' || '❌ Failed' }}\n\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
