name: Build Spring Boot Docker Image (Reusable)

on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
        default: 'app-artifact'
        description: 'Name of the uploaded artifact to use'
      image-name:
        required: true
        type: string
        description: 'Name of the Docker image to build'
      image-tag:
        required: false
        type: string
        default: 'latest'
        description: 'Tag for the Docker image'
      dockerfile-path:
        required: false
        type: string
        default: 'Dockerfile'
        description: 'Path to the Dockerfile'
      java-version:
        required: false
        type: string
        default: '17'
        description: 'Java version for the Docker image'
      spring-profiles:
        required: false
        type: string
        default: ''
        description: 'Spring profiles to activate'
      registry:
        required: false
        type: string
        default: 'ghcr.io'
        description: 'Container registry URL'
      push-image:
        required: false
        type: boolean
        default: true
        description: 'Whether to push the image to registry'

jobs:
  build-docker:
    name: Build Spring Boot Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./artifacts

      - name: Extract Spring Boot JAR
        run: |
          mkdir -p ./app
          if [[ -f ./artifacts/*.zip ]]; then
            unzip ./artifacts/*.zip -d ./app
          elif [[ -f ./artifacts/*.jar ]]; then
            cp ./artifacts/*.jar ./app/
          else
            echo "No JAR or ZIP found in artifacts directory"
            ls -la ./artifacts
            exit 1
          fi
          echo "Extracted application files:"
          ls -la ./app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        if: ${{ inputs.push-image }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile-path }}
          push: ${{ inputs.push-image }}
          tags: ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
          build-args: |
            JAR_FILE=./app/*.jar
            JAVA_VERSION=${{ inputs.java-version }}
            SPRING_PROFILES_ACTIVE=${{ inputs.spring-profiles }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo "Spring Boot Docker image built and pushed with tag ${{ inputs.image-tag }}"