name: Handle Push Events

on:
  push:
    branches:
      - main
      - dev
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'

jobs:
  # Call reusable workflow to get environment information
  determine-environment:
    uses: ./.github/workflows/environment.yaml
    with:
      branch_name: ${{ github.ref_name }}
  
  # Build the Java application
  build-and-deploy:
    needs: determine-environment
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event info
        run: |
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Ref Name: ${{ github.ref_name }}"
          echo "GitHub SHA: ${{ github.sha }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Workflow: ${{ github.workflow }}"
          echo "GitHub Workspace: ${{ github.workspace }}"
          echo "GitHub Event Path: ${{ github.event_path }}" 
          echo "environment: ${{ needs.determine-environment.outputs.environment }}"
          echo "Artifact name: ${{ needs.determine-environment.outputs.deploy }}"

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: |
          
          mvn -B package --file pom.xml
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: target/*.jar
      