name: Handle Push Events

on:
  push:
    branches:
      - main
      - dev
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'

jobs:
  # Call reusable workflow to get environment information
  determine-environment:
    uses: ./.github/workflows/environment.yaml
    with:
      branch_name: ${{ github.ref_name }}

  determine-version:
    uses: ./.github/workflows/version.yaml
    with:
      java-version: '17'

  print-github-info:
    needs: [determine-version, determine-environment]
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event info
        run: |
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Ref Name: ${{ github.ref_name }}"
          echo "GitHub SHA: ${{ github.sha }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Workflow: ${{ github.workflow }}"
          echo "GitHub Workspace: ${{ github.workspace }}"
          echo "GitHub Event Path: ${{ github.event_path }}" 
          echo "Environment: ${{ needs.calculate-environment.outputs.environment }}"
          echo "Need Deploy: ${{ needs.calculate-environment.outputs.deploy }}"
          echo "Version: ${{ needs.determine-version.outputs.version }}"
  
  # Build the Java application
  build-java:
    needs: [print-github-info, determine-version]
    uses: ./.github/workflows/build.yaml
    with:
      version-args: ${{ needs.determine-version.outputs.version }}
      java-version: '17'

