name: Handle Push Events

on:
  push:
    branches:
      - main
      - dev
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'

jobs:
  print-github-info:
    name: Print GitHub Info
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event info
        run: |
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Ref Name: ${{ github.ref_name }}"
          echo "GitHub SHA: ${{ github.sha }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Workflow: ${{ github.workflow }}"
          echo "GitHub Workspace: ${{ github.workspace }}"
          echo "GitHub Event Path: ${{ github.event_path }}" 

  # Call reusable workflow to get environment information
  determine-environment:
    name: Determine Environment
    uses: ./.github/workflows/environment.yaml
    with:
      branch_name: ${{ github.ref_name }}

  print-environment-info:
    name: Print Environment Info
    needs: [ determine-environment ]
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event info
        run: |
          echo "Environment: ${{ needs.determine-environment.outputs.environment }}"
          echo "Need Deploy: ${{ needs.determine-environment.outputs.deploy }}"
          echo "UAT: ${{ needs.calculate-environment.outputs.is_uat }}"
          echo "Staging: ${{ needs.determine-environment.outputs.is_staging }}"
          echo "Development: ${{ needs.calculate-environment.outputs.is_development }}"
          echo "Production: ${{ needs.calculate-environment.outputs.is_production }}"

  determine-version:
    name: Determine Version
    uses: ./.github/workflows/version.yaml
    with:
      java-version: '17'

  print-version-info:
    name: Print Version Info
    needs: [determine-version]
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event info
        run: |
          echo "Version: ${{ needs.determine-version.outputs.version }}"
  
  # Build the Java application
  build-java:
    name: Build Java Application
    needs: [determine-version]
    uses: ./.github/workflows/build.yaml
    with:
      version-args: ${{ needs.determine-version.outputs.version }}
      java-version: '17'

